//Author: Jainil Sevalia(jn498899@dal.ca) || Banner Id: B00925445

import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#789ADFG89",
    transactionName: "Ice-Cream",
    transactionAmount: 50,
  },
  {
    tripId: 1,
    transactionId: "#856GLASD8",
    transactionName: "Break-Fast",
    transactionAmount: 70,
  },
  {
    tripId: 2,
    transactionId: "#654HAKD89",
    transactionName: "Lunch",
    transactionAmount: 80,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 2,
    transactionId: "#878FDSD98",
    transactionName: "Dinner",
    transactionAmount: 100,
  },
  {
    tripId: 3,
    transactionId: "#546ASDK85",
    transactionName: "Shopping",
    transactionAmount: 50,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 3,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 4,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 5,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 6,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 7,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 8,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
  {
    tripId: 8,
    transactionId: "#645ASDA45",
    transactionName: "Gas",
    transactionAmount: 200,
  },
];

const Transaction = createSlice({
  name: "transaction",
  initialState: initialState,
  reducers: {
    addTransaction: (state, action) => {
      state.push(action.payload);
    },
  },
});

export const { addTransaction } = Transaction.actions;
export default Transaction.reducer;
